/* test_cbnorm.c — cross-checks for the eig-free certified eta-idempotence
 * bracket (bead aic-m24, increment 1). The bracket
 *     [ ||J||_F / n ,  2 * ||J||_F ]   with J = Choi(Phi^2 - Phi)  (n^2 x n^2)
 * must rigorously contain eta = ||Phi^2-Phi||_cb (= ||.||_diamond), .tex:347-354.
 *
 * Golden master: tests/fixtures_d24.inc.h (17 fixtures, generated by the Julia +
 * MOSEK Watrous-SDP generator; each carries the channel Kraus ops, the reference
 * Convention-A Choi of Lambda = Phi^2 - Phi, and the diamond-norm eta_ref).
 *
 * Assertion families:
 *   (A) CORRECTNESS / validity: build J from the fixture's stored golden Choi,
 *       call the routine, assert lo <= eta_ref <= hi (tiny slack for the SDP
 *       solver tolerance). Validates the MATH (wrong n-power / sign misses).
 *   (B) TEETH / exactness: independently recompute fF = ||J||_F by a direct
 *       double sum over the stored Choi arrays; assert lo == fF/n and hi == 2*fF
 *       to ~1e-12. Pins BOTH constants (the 1/n and the factor 2).
 *   (C) eta=0 oracle: for eta_is_zero fixtures, J~0 so the bracket collapses to
 *       ~[0,0]: assert arb_upper(hi) < 1e-9.
 *   (D) precision self-consistency: prec=53 vs prec=256 on a couple of fixtures
 *       both bracket fF/n and 2*fF.
 *   (E) wrapper path: aic_cbnorm_eigfree_ball (rebuilds Phi from Kraus, runs
 *       compose + choi_diff) agrees with the choi-level path within ~1e-9.
 */
#include <math.h>
#include <string.h>

#include <flint/acb.h>
#include <flint/acb_mat.h>
#include <flint/arb.h>
#include <flint/arf.h>

#include "aic/aic_cbnorm.h"
#include "aic/aic_ucp.h"
#include "aic_test.h"

#include "fixtures_d24.inc.h"

#define PREC 53

/* Two arb balls agree within tol iff the ball |a-b| is certainly <= tol
 * (rigorous, by arb_le semantics — same idea as aic_acb_close for acb). */
static int arb_close(const arb_t a, const arb_t b, const arb_t tol)
{
    arb_t d;
    arb_init(d);
    arb_sub(d, a, b, 64);
    arb_abs(d, d);
    int ok = arb_le(d, tol);
    arb_clear(d);
    return ok;
}

/* lower/upper endpoints of an arb ball as doubles (for the family-(C) bound and
 * cross-path comparisons; the rigorous bracket lives in the arb balls). */
static double arb_lo_d(const arb_t x)
{
    arf_t t;
    arf_init(t);
    arb_get_lbound_arf(t, x, 64);
    double v = arf_get_d(t, ARF_RND_FLOOR);
    arf_clear(t);
    return v;
}
static double arb_hi_d(const arb_t x)
{
    arf_t t;
    arf_init(t);
    arb_get_ubound_arf(t, x, 64);
    double v = arf_get_d(t, ARF_RND_CEIL);
    arf_clear(t);
    return v;
}

/* Build the golden Choi(Lambda) (N x N, N=n*n) into an acb_mat from a fixture. */
static void build_choi_from_fixture(acb_mat_t J, const aic_d24_fixture *f)
{
    slong N = f->n * f->n;
    for (slong p = 0; p < N; p++)
        for (slong q = 0; q < N; q++)
            acb_set_d_d(acb_mat_entry(J, p, q),
                        f->choi_re[p * N + q], f->choi_im[p * N + q]);
}

/* Build the channel Phi from a fixture's Kraus ops (aic_ucp layout, as in
 * test_ucp_d24.c). */
static void build_kraus_from_fixture(aic_ucp_kraus *phi, const aic_d24_fixture *f)
{
    aic_ucp_kraus_init(phi, f->n, f->n, f->r);
    for (slong a = 0; a < f->r; a++)
        for (slong i = 0; i < f->n; i++)
            for (slong j = 0; j < f->n; j++) {
                slong off = a * f->n * f->n + i * f->n + j;
                acb_set_d_d(acb_mat_entry(phi->K[a], i, j),
                            f->kraus_re[off], f->kraus_im[off]);
            }
}

/* Direct double recomputation of fF = ||J||_F from the stored Choi arrays —
 * INDEPENDENT of the C routine (which uses acb_mat_frobenius_norm). */
static double fro_from_fixture(const aic_d24_fixture *f)
{
    slong N = f->n * f->n;
    double s = 0.0;
    for (slong k = 0; k < N * N; k++)
        s += f->choi_re[k] * f->choi_re[k] + f->choi_im[k] * f->choi_im[k];
    return sqrt(s);
}

int main(void)
{
    double worst_lo_err = 0.0;     /* max |arb_mid(lo) - fF/n| over corpus */
    double worst_hi_err = 0.0;     /* max |arb_mid(hi) - 2*fF|             */
    double tightest_A_margin = 1e300; /* min (hi_upper - eta_ref) over A    */

    for (int fi = 0; fi < AIC_D24_NFIX; fi++) {
        const aic_d24_fixture *f = &aic_d24_fixtures[fi];
        slong n = f->n, N = n * n;
        double fF = fro_from_fixture(f);

        acb_mat_t J;
        acb_mat_init(J, N, N);
        build_choi_from_fixture(J, f);

        arb_t lo, hi;
        arb_init(lo);
        arb_init(hi);
        aic_cbnorm_eigfree_ball_choi(lo, hi, J, n, PREC);

        /* --- family (A): rigorous containment of the golden eta_ref --- */
        /* lo <= eta_ref + slack  AND  eta_ref - slack <= hi, with a tiny slack
         * (~1e-7) for the SDP solver tolerance baked into eta_ref. */
        {
            double lo_lb = arb_lo_d(lo);
            double hi_ub = arb_hi_d(hi);
            const double slack = 1e-7;
            AIC_CHECK_MSG(lo_lb <= f->eta_ref + slack,
                          "(A) fixture %s: lo=%.6e > eta_ref=%.6e (lower bound "
                          "exceeds eta!)", f->name, lo_lb, f->eta_ref);
            AIC_CHECK_MSG(f->eta_ref - slack <= hi_ub,
                          "(A) fixture %s: hi=%.6e < eta_ref=%.6e (upper bound "
                          "below eta!)", f->name, hi_ub, f->eta_ref);
            double margin = hi_ub - f->eta_ref;
            if (!f->eta_is_zero && margin < tightest_A_margin)
                tightest_A_margin = margin;
        }

        /* --- family (B): pin both constants. lo brackets fF/n, hi brackets
         * 2*fF, to ~1e-12 (the routine's lo == fF/n and hi == 2*fF exactly). */
        {
            arb_t ref;
            arb_t tol;
            arb_init(ref);
            arb_init(tol);
            arb_set_d(tol, 1e-12);

            arb_set_d(ref, fF / (double) n);
            AIC_CHECK_DOUBLE_CLOSE(fF / (double) n, lo, tol);
            AIC_CHECK_MSG(arb_lo_d(lo) <= fF / (double) n + 1e-12 &&
                          fF / (double) n - 1e-12 <= arb_hi_d(lo),
                          "(B) fixture %s: lo ball does not bracket fF/n", f->name);

            arb_set_d(ref, 2.0 * fF);
            AIC_CHECK_DOUBLE_CLOSE(2.0 * fF, hi, tol);
            AIC_CHECK_MSG(arb_lo_d(hi) <= 2.0 * fF + 1e-12 &&
                          2.0 * fF - 1e-12 <= arb_hi_d(hi),
                          "(B) fixture %s: hi ball does not bracket 2*fF", f->name);

            arb_clear(tol);
            arb_clear(ref);

            /* track worst midpoint errors for the report. */
            double lo_mid = 0.5 * (arb_lo_d(lo) + arb_hi_d(lo));
            double hi_mid = 0.5 * (arb_lo_d(hi) + arb_hi_d(hi));
            double e_lo = fabs(lo_mid - fF / (double) n);
            double e_hi = fabs(hi_mid - 2.0 * fF);
            if (e_lo > worst_lo_err) worst_lo_err = e_lo;
            if (e_hi > worst_hi_err) worst_hi_err = e_hi;
        }

        /* --- family (C): eta=0 oracle: bracket collapses to ~[0,0] --- */
        if (f->eta_is_zero) {
            AIC_CHECK_MSG(arb_hi_d(hi) < 1e-9,
                          "(C) fixture %s: eta=0 oracle but hi=%.3e !< 1e-9",
                          f->name, arb_hi_d(hi));
        }

        arb_clear(hi);
        arb_clear(lo);
        acb_mat_clear(J);
    }

    /* --- family (D): precision self-consistency (prec=53 vs prec=256) on a
     * couple of representative fixtures (one n=2 nonzero, one n=4 nonzero). */
    {
        const char *targets[] = {"phi_t_0p3", "phi_t4_0p2"};
        for (int ti = 0; ti < 2; ti++) {
            for (int fi = 0; fi < AIC_D24_NFIX; fi++) {
                const aic_d24_fixture *f = &aic_d24_fixtures[fi];
                if (strcmp(f->name, targets[ti]) != 0) continue;
                slong n = f->n, N = n * n;
                double fF = fro_from_fixture(f);
                acb_mat_t J;
                acb_mat_init(J, N, N);
                build_choi_from_fixture(J, f);

                arb_t lo53, hi53, lo256, hi256, tol;
                arb_init(lo53); arb_init(hi53);
                arb_init(lo256); arb_init(hi256);
                arb_init(tol);
                arb_set_d(tol, 1e-12);
                aic_cbnorm_eigfree_ball_choi(lo53, hi53, J, n, 53);
                aic_cbnorm_eigfree_ball_choi(lo256, hi256, J, n, 256);

                AIC_CHECK_DOUBLE_CLOSE(fF / (double) n, lo53, tol);
                AIC_CHECK_DOUBLE_CLOSE(fF / (double) n, lo256, tol);
                AIC_CHECK_DOUBLE_CLOSE(2.0 * fF, hi53, tol);
                AIC_CHECK_DOUBLE_CLOSE(2.0 * fF, hi256, tol);

                arb_clear(tol);
                arb_clear(hi256); arb_clear(lo256);
                arb_clear(hi53); arb_clear(lo53);
                acb_mat_clear(J);
            }
        }
    }

    /* --- family (E): wrapper path (Phi -> Phi^2 -> J -> ball) agrees with the
     * choi-level path within ~1e-9, on a few fixtures spanning dims. */
    {
        const char *targets[] = {"phi_t_0p3", "complex_qubit", "phi_t4_0p2",
                                 "block_lowrank3"};
        for (int ti = 0; ti < 4; ti++) {
            for (int fi = 0; fi < AIC_D24_NFIX; fi++) {
                const aic_d24_fixture *f = &aic_d24_fixtures[fi];
                if (strcmp(f->name, targets[ti]) != 0) continue;
                slong n = f->n, N = n * n;

                /* choi-level path from the stored golden Choi */
                acb_mat_t J;
                acb_mat_init(J, N, N);
                build_choi_from_fixture(J, f);
                arb_t loC, hiC;
                arb_init(loC); arb_init(hiC);
                aic_cbnorm_eigfree_ball_choi(loC, hiC, J, n, PREC);

                /* wrapper path: rebuild Phi, run compose + choi_diff internally */
                aic_ucp_kraus phi;
                build_kraus_from_fixture(&phi, f);
                arb_t loW, hiW;
                arb_init(loW); arb_init(hiW);
                aic_cbnorm_eigfree_ball(loW, hiW, &phi, PREC);

                arb_t tol;
                arb_init(tol);
                arb_set_d(tol, 1e-9);
                AIC_CHECK_MSG(arb_close(loW, loC, tol),
                              "(E) fixture %s: wrapper lo != choi-level lo",
                              f->name);
                AIC_CHECK_MSG(arb_close(hiW, hiC, tol),
                              "(E) fixture %s: wrapper hi != choi-level hi",
                              f->name);
                arb_clear(tol);

                arb_clear(hiW); arb_clear(loW);
                aic_ucp_kraus_clear(&phi);
                arb_clear(hiC); arb_clear(loC);
                acb_mat_clear(J);
            }
        }
    }

    printf("CHECKS test_cbnorm n=%ld\n", aic_test_checks);
    printf("worst |lo_mid - fF/n| = %.3e, worst |hi_mid - 2fF| = %.3e\n",
           worst_lo_err, worst_hi_err);
    printf("tightest family-A upper margin (hi - eta_ref) = %.6e\n",
           tightest_A_margin);
    aic_test_report("test_cbnorm");
    printf("OK test_cbnorm\n");
    return 0;
}
