/* test_certify.c — cross-checks for the TIGHT certified eta-idempotence ball
 * (bead aic-m24, increment 3b). The tight bracket [lo,hi] from
 * aic_cbnorm_certify (src/aic_cbnorm_certify.c) must RIGOROUSLY contain
 * eta = ||Phi^2-Phi||_cb (= ||.||_diamond, .tex:347-354) AND be much tighter
 * than the eig-free 2n-wide bracket. See docs/research/cbnorm_tight_certifier.md.
 *
 * Golden master: tests/fixtures_certify.inc.h (5 channels; generated by
 * tools/gen_fixtures_certify.jl with MOSEK). Each carries the Kraus ops, eta_ref,
 * and two SDP feasible points: MAX-primal (X,P,Q) and MIN-dual (Y0,Y1). The
 * paper_0p1 fixture (the paper example, .tex:367-378) has ASYMMETRIC dual
 * marginals and is the GAP-1 direction-teeth fixture (family F).
 *
 * Assertion families:
 *   (A) CONTAINMENT: arb_lower(lo) <= eta_ref + 1e-7 AND eta_ref - 1e-7 <=
 *       arb_upper(hi) (rigorous bracket contains the golden value).
 *   (B) TIGHTNESS: non-eta=0 fixtures, arb_upper(hi) - arb_lower(lo) < 1e-4
 *       (the tight ball; the gap is ~MOSEK gap + arb radius).
 *   (C) eta=0 (id_2): arb_upper(hi) < 1e-9.
 *   (D) double-vs-arb: prec=64 vs prec=256 on phi_t4_0p2 both bracket eta_ref;
 *       widths agree in order of magnitude.
 *   (E) UNIVERSALITY canary: tight relative width (hi-lo)/eta_ref does NOT grow
 *       with n (phi_t_0p3 n=2 vs phi_t4_0p2 n=4).
 *   (F) PARTIAL-TRACE DIRECTION teeth (GAP 1): paper_0p1's dual marginal is
 *       asymmetric (>= 0.05); the symmetric fixtures stay < 1e-9. Swapping
 *       partial_trace_right->left turns (B) RED on paper_0p1 only (mutation-proven).
 *   (G) RESTORATION-CORRECTION teeth (GAP 2): synthetic in-test perturbation forces
 *       delta>0 / t<1 (LOWER) and eps>0 (UPPER); the corrected bound STILL brackets
 *       eta_ref (rigor preserved). Dropping t / +eps*n turns (G) RED (mutation-proven).
 *
 * NOTE (>200 LOC): this test file exceeds the Rule-10 200-LOC limit (like the
 * sibling test files); flagged for aic-w4o.4. The SOURCE cores stay under 200.
 */
#include <math.h>
#include <string.h>

#include <flint/acb.h>
#include <flint/acb_mat.h>
#include <flint/arb.h>
#include <flint/arf.h>

#include "aic/aic_cbnorm.h"
#include "aic/aic_mat.h"
#include "aic/aic_ucp.h"
#include "aic_test.h"

/* GAP 2 (synthetic-perturbation correction tests) calls the internal recipes
 * directly to read off the restoration defects delta (LOWER) and eps (UPPER) and
 * the t-scaling — the public aic_cbnorm_certify hides them. The internal header
 * is under src/ (not a public surface), reached by relative path here only. */
#include "../src/aic_cbnorm_internal.h"

#include "fixtures_certify.inc.h"

#define PREC 128

/* lower/upper endpoints of an arb ball as doubles (rigorous: FLOOR / CEIL). */
static double arb_lo_d(const arb_t x)
{
    arf_t t;
    arf_init(t);
    arb_get_lbound_arf(t, x, 64);
    double v = arf_get_d(t, ARF_RND_FLOOR);
    arf_clear(t);
    return v;
}
static double arb_hi_d(const arb_t x)
{
    arf_t t;
    arf_init(t);
    arb_get_ubound_arf(t, x, 64);
    double v = arf_get_d(t, ARF_RND_CEIL);
    arf_clear(t);
    return v;
}

/* Load a flat N x N [p*N+q] (re,im) array into an acb_mat. */
static void load_NN(acb_mat_t M, const double *re, const double *im, slong N)
{
    for (slong p = 0; p < N; p++)
        for (slong q = 0; q < N; q++)
            acb_set_d_d(acb_mat_entry(M, p, q), re[p * N + q], im[p * N + q]);
}

/* Build J = Choi(Phi^2 - Phi) from the fixture's Kraus ops (the arb path the
 * shim uses), into a caller-initialised N x N acb_mat. */
static void build_J(acb_mat_t J, const aic_certify_fixture *f, slong prec)
{
    aic_ucp_kraus phi, phi2;
    aic_ucp_kraus_init(&phi, f->n, f->n, f->r);
    for (slong a = 0; a < f->r; a++)
        for (slong i = 0; i < f->n; i++)
            for (slong j = 0; j < f->n; j++) {
                slong off = a * f->n * f->n + i * f->n + j;
                acb_set_d_d(acb_mat_entry(phi.K[a], i, j),
                            f->kraus_re[off], f->kraus_im[off]);
            }
    aic_ucp_compose(&phi2, &phi, &phi, prec);
    aic_ucp_choi_diff(J, &phi2, &phi, prec);
    aic_ucp_kraus_clear(&phi2);
    aic_ucp_kraus_clear(&phi);
}

/* Find a committed fixture by name (fail loud if absent — Rule 4). */
static const aic_certify_fixture *find_fixture(const char *name)
{
    for (int fi = 0; fi < AIC_CERTIFY_NFIX; fi++)
        if (strcmp(aic_certify_fixtures[fi].name, name) == 0)
            return &aic_certify_fixtures[fi];
    AIC_FAIL("fixture %s not found", name);
    return NULL;
}

/* arb-ball upper endpoint of (2/n) Re tr(J^dag X): the RAW (uncorrected) LOWER
 * objective. Used to prove the t-scaling actually shrank the bound (t < 1). */
static double raw_lower_d(const acb_mat_t J, const acb_mat_t X, slong n, slong prec)
{
    slong N = n * n;
    acb_mat_t Jd, M;
    acb_mat_init(Jd, N, N); acb_mat_init(M, N, N);
    acb_mat_conjugate_transpose(Jd, J);
    acb_mat_mul(M, Jd, X, prec);
    acb_t tr;
    acb_init(tr);
    acb_mat_trace(tr, M, prec);
    arb_t re;
    arb_init(re);
    acb_get_real(re, tr);
    arb_mul_2exp_si(re, re, 1);
    arb_div_ui(re, re, (ulong) n, prec);
    double v = arb_hi_d(re);
    arb_clear(re); acb_clear(tr);
    acb_mat_clear(M); acb_mat_clear(Jd);
    return v;
}

/* Run the certifier on one fixture at a given prec; return [lo,hi] doubles. */
static void certify_fixture(const aic_certify_fixture *f, slong prec,
                            double *lo_lb, double *hi_ub)
{
    slong n = f->n, N = n * n;
    acb_mat_t J, X, P, Q, Y0, Y1;
    acb_mat_init(J, N, N);
    acb_mat_init(X, N, N); acb_mat_init(P, N, N); acb_mat_init(Q, N, N);
    acb_mat_init(Y0, N, N); acb_mat_init(Y1, N, N);

    build_J(J, f, prec);
    load_NN(X, f->X_re, f->X_im, N);
    load_NN(P, f->P_re, f->P_im, N);
    load_NN(Q, f->Q_re, f->Q_im, N);
    load_NN(Y0, f->Y0_re, f->Y0_im, N);
    load_NN(Y1, f->Y1_re, f->Y1_im, N);

    arb_t lo, hi;
    arb_init(lo); arb_init(hi);
    aic_cbnorm_certify(lo, hi, J, X, P, Q, Y0, Y1, n, prec);

    *lo_lb = arb_lo_d(lo);
    *hi_ub = arb_hi_d(hi);

    arb_clear(hi); arb_clear(lo);
    acb_mat_clear(Y1); acb_mat_clear(Y0);
    acb_mat_clear(Q); acb_mat_clear(P); acb_mat_clear(X);
    acb_mat_clear(J);
}

int main(void)
{
    double rel_width_n2 = -1.0, rel_width_n4 = -1.0;

    for (int fi = 0; fi < AIC_CERTIFY_NFIX; fi++) {
        const aic_certify_fixture *f = &aic_certify_fixtures[fi];
        double lo_lb, hi_ub;
        certify_fixture(f, PREC, &lo_lb, &hi_ub);
        double width = hi_ub - lo_lb;

        printf("  %-14s n=%ld  [lo,hi]=[% .12e, % .12e]  width=%.3e  "
               "eta_ref=%.6e\n",
               f->name, (long) f->n, lo_lb, hi_ub, width, f->eta_ref);

        /* (A) CONTAINMENT: rigorous bracket contains eta_ref (1e-7 MOSEK slack). */
        const double slack = 1e-7;
        AIC_CHECK_MSG(lo_lb <= f->eta_ref + slack,
                      "(A) %s: lo=%.10e > eta_ref=%.10e (lower bound exceeds eta)",
                      f->name, lo_lb, f->eta_ref);
        AIC_CHECK_MSG(f->eta_ref - slack <= hi_ub,
                      "(A) %s: hi=%.10e < eta_ref=%.10e (upper bound below eta)",
                      f->name, hi_ub, f->eta_ref);

        if (!f->eta_is_zero) {
            /* (B) TIGHTNESS: much tighter than the eig-free 2n-wide bracket. */
            AIC_CHECK_MSG(width < 1e-4,
                          "(B) %s: tight width=%.3e !< 1e-4", f->name, width);

            /* (E) universality: collect relative widths for n=2 and n=4. */
            double rel = width / f->eta_ref;
            if (strcmp(f->name, "phi_t_0p3") == 0) rel_width_n2 = rel;
            if (strcmp(f->name, "phi_t4_0p2") == 0) rel_width_n4 = rel;
        } else {
            /* (C) eta=0 oracle: bracket collapses to ~[0,0]. */
            AIC_CHECK_MSG(hi_ub < 1e-9,
                          "(C) %s: eta=0 oracle but hi=%.3e !< 1e-9",
                          f->name, hi_ub);
        }
    }

    /* (D) double-vs-arb: prec=64 vs prec=256 on phi_t4_0p2. */
    {
        const aic_certify_fixture *f = NULL;
        for (int fi = 0; fi < AIC_CERTIFY_NFIX; fi++)
            if (strcmp(aic_certify_fixtures[fi].name, "phi_t4_0p2") == 0)
                f = &aic_certify_fixtures[fi];
        AIC_CHECK(f != NULL);

        double lo64, hi64, lo256, hi256;
        certify_fixture(f, 64, &lo64, &hi64);
        certify_fixture(f, 256, &lo256, &hi256);
        const double slack = 1e-7;
        AIC_CHECK_MSG(lo64 <= f->eta_ref + slack && f->eta_ref - slack <= hi64,
                      "(D) prec=64 does not bracket eta_ref");
        AIC_CHECK_MSG(lo256 <= f->eta_ref + slack && f->eta_ref - slack <= hi256,
                      "(D) prec=256 does not bracket eta_ref");
        double w64 = hi64 - lo64, w256 = hi256 - lo256;
        /* widths agree in order of magnitude (both ~ MOSEK gap, prec-insensitive
         * since the double feasible point sets the floor). */
        AIC_CHECK_MSG(w64 > 0 && w256 > 0 &&
                      w64 / w256 < 1e3 && w256 / w64 < 1e3,
                      "(D) prec=64 vs 256 widths differ by >1e3: %.3e vs %.3e",
                      w64, w256);
        printf("  (D) phi_t4_0p2  width@64=%.3e  width@256=%.3e\n", w64, w256);
    }

    /* (E) UNIVERSALITY canary: relative tight width does NOT grow with n. */
    AIC_CHECK(rel_width_n2 > 0 && rel_width_n4 > 0);
    AIC_CHECK_MSG(rel_width_n4 < 100.0 * rel_width_n2,
                  "(E) relative width grows with n: n=2 %.3e vs n=4 %.3e",
                  rel_width_n2, rel_width_n4);
    printf("  (E) rel-width n=2 (phi_t_0p3) = %.3e,  n=4 (phi_t4_0p2) = %.3e\n",
           rel_width_n2, rel_width_n4);

    /* (F) PARTIAL-TRACE-DIRECTION teeth (GAP 1 closed; design doc Risk #5).
     * The UPPER bound uses Tr_2 = aic_mat_partial_trace_right (RIGHT/input factor).
     * The teeth test is: swap right->left in src/aic_cbnorm_certify_restore.c and
     * an ASYMMETRIC-marginal fixture must go RED. On a SYMMETRIC fixture the two
     * marginals coincide (||Tr_R(Y0)-Tr_L(Y0)||_F ~ 1e-13) so the swap is silent —
     * which is why the earlier 4-channel corpus had no teeth. The paper_0p1
     * fixture has GENUINELY asymmetric marginals (~0.134), so with the wrong
     * direction Tr_L gives hi = 2*eta and the (B) tightness check above
     * (width 9.487e-02 !< 1e-4) goes RED. MUTATION-PROVEN: right->left in
     * aic_cbnorm_int_upper turns test_certify RED on paper_0p1.
     *
     * Here we ASSERT the corpus precondition that makes those teeth real:
     *   - paper_0p1's marginal is asymmetric (>= 0.05) -> the swap is observable;
     *   - the symmetric fixtures stay near 0 (< 1e-9) -> the swap is silent there,
     *     so paper_0p1 is the channel that catches the direction (Rule 7: a test
     *     that would catch a real regression). A future regeneration that loses
     *     the asymmetry would here fail loudly rather than silently disarm GAP 1. */
    printf("  (F) Tr_2-direction teeth: ||Tr_R(Y0)-Tr_L(Y0)||_F per fixture "
           "(asymmetric fixture catches the right->left swap):\n");
    int seen_asym = 0;
    for (int fi = 0; fi < AIC_CERTIFY_NFIX; fi++) {
        const aic_certify_fixture *f = &aic_certify_fixtures[fi];
        slong n = f->n, N = n * n;
        acb_mat_t Y0, TR, TL;
        acb_mat_init(Y0, N, N);
        acb_mat_init(TR, n, n); acb_mat_init(TL, n, n);
        load_NN(Y0, f->Y0_re, f->Y0_im, N);
        aic_mat_partial_trace_right(TR, Y0, n, n, PREC);
        aic_mat_partial_trace_left(TL, Y0, n, n, PREC);
        acb_mat_sub(TR, TR, TL, PREC);
        arb_t d;
        arb_init(d);
        aic_mat_frobenius_norm(d, TR, PREC);
        double asym = arb_hi_d(d);
        printf("        %-14s ||Tr_R-Tr_L||_F = %.3e\n", f->name, asym);
        if (strcmp(f->name, "paper_0p1") == 0) {
            /* The asymmetric fixture: this is what gives the direction teeth. */
            AIC_CHECK_MSG(asym >= 0.05,
                          "(F) paper_0p1 marginal asym=%.3e < 0.05 (teeth gone)",
                          asym);
            seen_asym = 1;
        } else {
            /* Symmetric fixtures: the swap is silent here (cannot catch it). */
            AIC_CHECK_MSG(asym < 1e-9,
                          "(F) %s unexpectedly asymmetric: %.3e", f->name, asym);
        }
        arb_clear(d);
        acb_mat_clear(TL); acb_mat_clear(TR); acb_mat_clear(Y0);
    }
    AIC_CHECK_MSG(seen_asym,
                  "(F) no asymmetric fixture present -> direction has no teeth");

    /* (G) SYNTHETIC-PERTURBATION CORRECTION teeth (GAP 2 closed; design doc
     * §"Jansson correction"). MOSEK is so accurate on this corpus that delta=0 and
     * eps<=7e-16, so the t-scaling (LOWER) and the +eps*n shift (UPPER) rigor-
     * corrections never fire — dead code with no proof. We can't ask MOSEK for an
     * infeasible point, so we MANUFACTURE one in-test and confirm: (i) the defect
     * goes strictly > 0 (the correction ACTIVATES), (ii) the corrected bound STILL
     * brackets eta_ref (rigor preserved under infeasibility — the whole point of
     * the restoration). The mutation proofs (dropping each correction -> RED) are
     * in the source-mutation log below the assertions. */
    printf("  (G) synthetic-perturbation correction teeth (GAP 2):\n");

    /* (G.LOWER) Scale X -> c*X (c>1): the primal block [[P',cX],[cX^dag,Q']] goes
     * non-PSD, so delta = max(0,-lambda_min) > 0 and t = 1/(1+2*delta) < 1. The raw
     * objective c*(2/n)Re tr(J^dag X) ~ c*eta would EXCEED eta; the t-scaling pulls
     * lo back below eta_ref. With t dropped (lo = raw, mutation), lo > eta_ref. */
    {
        const aic_certify_fixture *f = find_fixture("phi_t_0p3");
        slong n = f->n, N = n * n;
        const double c = 2.0;     /* enough to break PSD on this fixture */
        acb_mat_t J, X, P, Q;
        acb_mat_init(J, N, N); acb_mat_init(X, N, N);
        acb_mat_init(P, N, N); acb_mat_init(Q, N, N);
        build_J(J, f, PREC);
        load_NN(X, f->X_re, f->X_im, N);
        load_NN(P, f->P_re, f->P_im, N);
        load_NN(Q, f->Q_re, f->Q_im, N);
        acb_mat_scalar_mul_si(X, X, (slong) c, PREC);     /* X -> c*X (c integer) */

        arb_t lo, delta;
        arb_init(lo); arb_init(delta);
        aic_cbnorm_int_lower(lo, delta, J, X, P, Q, n, PREC);
        double lo_corr = arb_hi_d(lo);
        double delta_lb = arb_lo_d(delta);
        double raw = raw_lower_d(J, X, n, PREC);          /* = c * eta_ref ~ 0.63 */
        printf("        LOWER  c=%.1f  delta(lb)=%.3e  raw(t=1)=%.6e  "
               "corrected lo=%.6e  eta_ref=%.6e\n",
               c, delta_lb, raw, lo_corr, f->eta_ref);

        const double slack = 1e-7;
        /* (i) correction ACTIVATED: delta > 0 (so t = 1/(1+2 delta) < 1). */
        AIC_CHECK_MSG(delta_lb > 1e-6,
                      "(G.LOWER) delta=%.3e not > 0: correction did not fire",
                      delta_lb);
        /* prove t<1 directly: the corrected bound is strictly below the raw one. */
        AIC_CHECK_MSG(lo_corr < raw - 1e-9,
                      "(G.LOWER) t-scaling inert: lo=%.6e !< raw=%.6e",
                      lo_corr, raw);
        /* (ii) RIGOR PRESERVED: lo still a valid lower bound on eta. */
        AIC_CHECK_MSG(lo_corr <= f->eta_ref + slack,
                      "(G.LOWER) rigor BROKEN: corrected lo=%.10e > eta_ref=%.10e",
                      lo_corr, f->eta_ref);
        /* MUTATION GUARD (documents the teeth): without the t-scaling the raw
         * bound c*eta_ref EXCEEDS eta_ref, so dropping t turns (ii) RED. */
        AIC_CHECK_MSG(raw > f->eta_ref + slack,
                      "(G.LOWER) mutation-guard vacuous: raw=%.6e !> eta_ref=%.6e "
                      "(perturbation too weak to exercise the correction)",
                      raw, f->eta_ref);

        arb_clear(delta); arb_clear(lo);
        acb_mat_clear(Q); acb_mat_clear(P);
        acb_mat_clear(X); acb_mat_clear(J);
    }

    /* (G.UPPER) Shift Y0,Y1 -> Y0-sI, Y1-sI (s>0): block_D = [[Y0,-J],[-J^dag,Y1]]
     * goes non-PSD, so eps = max(0,-lambda_min) > 0. Tr_R(Y-sI_N) = Tr_R(Y)-s*n*I_n,
     * so the marginal max-eig drops by s*n; the +eps*n shift (eps = s) restores it.
     * With +eps*n dropped (mutation), hi = hi_orig - s*n < eta_ref. */
    {
        const aic_certify_fixture *f = find_fixture("phi_t_0p3");
        slong n = f->n, N = n * n;
        const double s = 0.05;    /* subtract s*I from Y0,Y1 -> block_D non-PSD */
        acb_mat_t J, Y0, Y1, sI;
        acb_mat_init(J, N, N);
        acb_mat_init(Y0, N, N); acb_mat_init(Y1, N, N); acb_mat_init(sI, N, N);
        build_J(J, f, PREC);
        load_NN(Y0, f->Y0_re, f->Y0_im, N);
        load_NN(Y1, f->Y1_re, f->Y1_im, N);
        acb_mat_one(sI);
        acb_t sc; acb_init(sc); acb_set_d(sc, s);
        acb_mat_scalar_mul_acb(sI, sI, sc, PREC);          /* s*I_N */
        acb_mat_sub(Y0, Y0, sI, PREC);
        acb_mat_sub(Y1, Y1, sI, PREC);
        acb_clear(sc);

        arb_t hi, eps;
        arb_init(hi); arb_init(eps);
        aic_cbnorm_int_upper(hi, eps, J, Y0, Y1, n, PREC);
        double hi_corr = arb_lo_d(hi);
        double eps_lb = arb_lo_d(eps);
        /* hi WITHOUT the +eps*n shift = (s0+s1)/2 = hi_corr - eps*n. eps ~ s, so
         * the dropped-shift bound ~ eta_ref - s*n: below eta_ref (RED). */
        double eps_ub = arb_hi_d(eps);
        double hi_noshift = arb_hi_d(hi) - eps_ub * (double) n;
        printf("        UPPER  s=%.2f  eps(lb)=%.3e  hi(no +eps*n)=%.6e  "
               "corrected hi=%.6e  eta_ref=%.6e\n",
               s, eps_lb, hi_noshift, arb_hi_d(hi), f->eta_ref);

        const double slack = 1e-7;
        /* (i) correction ACTIVATED: eps > 0. */
        AIC_CHECK_MSG(eps_lb > 1e-6,
                      "(G.UPPER) eps=%.3e not > 0: correction did not fire",
                      eps_lb);
        /* (ii) RIGOR PRESERVED: hi still a valid upper bound on eta. */
        AIC_CHECK_MSG(hi_corr >= f->eta_ref - slack,
                      "(G.UPPER) rigor BROKEN: corrected hi=%.10e < eta_ref=%.10e",
                      hi_corr, f->eta_ref);
        /* MUTATION GUARD: without +eps*n the bound dips BELOW eta_ref -> RED. */
        AIC_CHECK_MSG(hi_noshift < f->eta_ref - slack,
                      "(G.UPPER) mutation-guard vacuous: hi_noshift=%.6e !< "
                      "eta_ref=%.6e (perturbation too weak)",
                      hi_noshift, f->eta_ref);

        arb_clear(eps); arb_clear(hi);
        acb_mat_clear(sI); acb_mat_clear(Y1); acb_mat_clear(Y0);
        acb_mat_clear(J);
    }

    printf("CHECKS test_certify n=%ld\n", aic_test_checks);
    aic_test_report("test_certify");
    printf("OK test_certify\n");
    return 0;
}
