# universality.jl — README plot 2 (Part D.2 script 2), THE headline.
#
# The th_main isomorphism constant c = iso_defect/η over a growing block-algebra
# family is FLAT — it does NOT grow with dim A (approximate_algebras.tex:484/460).
# The naive averaging route the paper warns against has a constant ∝ n; this one
# does not.
#
# DATA SOURCE (honest): the verified C dim-sweep regression tests/test_dbo3.c at
# prec=256 (the block family ⊕_j M_d, dim_A = k·d²). The five anchor points and the
# OLS slope below were REGENERATED by running build/tests/test_dbo3 on 2026-06-02:
#     dim_A=8  c=0.018186   (k=2,d=2)
#     dim_A=12 c=0.047046   (k=3,d=2)   <- worst case
#     dim_A=16 c=0.024679   (k=4,d=2)
#     dim_A=18 c=0.041010   (k=2,d=3)
#     dim_A=20 c=0.013350   (k=5,d=2)
#     OLS slope b = -2.707458e-4 ;  max c = 0.047046 ;  c0 = 2.2732e-3
# A pure-Julia main_isomorphism sweep reproduces the same FLAT trend (smaller c,
# decreasing with dim, measured in probe_universality.jl); the C anchors are
# plotted because they are the verified prec=256 reference the README is written
# around. Palette: Part E. Writes ONE 640 px PNG.

using CairoMakie

# ---- Part E.2 unified theme (verbatim) ----
set_theme!(Theme(
    backgroundcolor = "#24283b",
    textcolor = "#c0caf5",
    Axis = (backgroundcolor="#1f2335", xgridcolor=("#565f89",0.4),
            ygridcolor=("#565f89",0.4), xtickcolor="#565f89", ytickcolor="#565f89",
            leftspinecolor="#565f89", bottomspinecolor="#565f89",
            topspinevisible=false, rightspinevisible=false),
    palette = (color = ["#7dcfff","#9ece6a","#bb9af7","#e0af68","#f7768e","#7aa2f7"],),
    fontsize = 15,
))

# ---- verified C anchors (build/tests/test_dbo3, prec=256, regenerated 2026-06-02) ----
dimA = [8.0, 12.0, 16.0, 18.0, 20.0]
c    = [0.018186, 0.047046, 0.024679, 0.041010, 0.013350]
slope = -2.707458e-4           # the test_dbo3 OLS fit (c vs dim_A)
# OLS intercept from the same fit (a = mean(c) - slope*mean(dimA)) for the line
xbar = sum(dimA) / length(dimA)
cbar = sum(c) / length(c)
intercept = cbar - slope * xbar
ols(x) = intercept + slope * x

println("OLS: slope=$slope  intercept=$(round(intercept; sigdigits=5))  max c=$(maximum(c))")

fig = Figure(size = (640, 430))
ax = Axis(fig[1, 1];
    title = "th_main isomorphism constant is flat over dimension  (approximate_algebras.tex:484)",
    titlesize = 13.5,
    xlabel = "dim A  (block family ⊕ M_d,  dim A = k·d²)",
    ylabel = "c = iso-defect / η")

# y-axis from 0 so flatness is unmistakable; a little headroom over max c
ylims!(ax, 0.0, 0.06)
xlims!(ax, 6.0, 22.0)

# OLS line (dashed, muted) UNDER the points
xline = range(6.0, 22.0; length = 50)
lols = lines!(ax, xline, ols.(xline); color = "#565f89", linestyle = :dash, linewidth = 2)

# the anchor scatter (teal, the primary series)
sc = scatter!(ax, dimA, c; color = "#7dcfff", markersize = 14, strokecolor = "#24283b", strokewidth = 1)

# annotate the worst case and the headline numbers
text!(ax, 12.0, 0.047046; text = "max c = 0.047  (dim A = 12)",
      align = (:left, :bottom), color = "#c0caf5", fontsize = 13, offset = (8, 4))
text!(ax, 21.5, 0.004; text = "OLS slope = −2.7e-4  →  no growth with dim",
      align = (:right, :bottom), color = "#9ece6a", fontsize = 13)

axislegend(ax,
    [sc, lols],
    ["c (C dim-sweep, test_dbo3, prec=256)", "OLS fit  (slope −2.7e-4)"];
    position = :rt, framevisible = false, labelcolor = "#c0caf5", patchsize = (18, 14))

out = "/home/tobias/Projects/almost-idempotent-channels/docs/src/assets/universality.png"
save(out, fig; px_per_unit = 2)
println("WROTE ", out)
